### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by maradona4** [PabloRNC/brawl-api-wrapper#2]
Someone help?

![image](https://github.com/PabloRNC/brawl-api-wrapper/assets/44541791/8784758d-45ed-4a68-a97a-c9c835738739)

**Comment by PabloRNC** [comment]
Hi, can you specify when is the error thrown. As it shows is a Brawl Stars' api internal error so this must be an error that is not related to the package.

**Comment by maradona4** [comment]
![image](https://github.com/PabloRNC/brawl-api-wrapper/assets/44541791/1c83a356-d41f-4f38-9e94-0a3a0fce9a47)
this here package.json

**Comment by PabloRNC** [comment]
Ok, but I want to know what are you doing when the error is thrown. Are you getting a brawler, or getting the info of a player? Let my know.

**Comment by PabloRNC** [comment]
Moreover furthermore I'm planning an update with all the new stuff from this year. As the new brawlers and changing the starPoints for blings. Also I'm planning to change all the package to give more freedom of using it.

**Comment by maradona4** [comment]
> Ok, but I want to know what are you doing when the error is thrown. Are you getting a brawler, or getting the info of a player? Let my know.

Yes get player id 
Physic Gear 5  -  TAG #VL0GPPJV

**Comment by PabloRNC** [comment]
I could see that this error is a non-related package error thrown when the package made the request of the battlelog's player. Its a brawl stars error so I can't do anything more than trying to contact supercell but there is no method to contact in regards of the api. The request of the player is made but it throws the error when fetching the battlelog.

The only thing to correct this is to give more freedom to the user and implement an elecion for the battlelog in the player.

**Comment by PabloRNC** [comment]
I'm updating the package right now as you can see in 54aac056b4cc41776adcb75c445bad380504fe96. So I could change it today.

**Comment by PabloRNC** [comment]
This error is solved in commit 4783a2d4d22e5011a7e1ae1f35d807f536148c12 when now you can select if you want to show the battlelog.

**Comment by PabloRNC** [comment]
I'm pushing an update now to the package.

**Comment by PabloRNC** [comment]
I just done the new release use ```npm i brawl-api-wrapper@latest ```

**Comment by maradona4** [comment]
Okay thank ^^

**Comment by maradona4** [comment]
![image](https://github.com/PabloRNC/brawl-api-wrapper/assets/44541791/b2a6cbac-42ac-4975-a400-0da227d7872e)
is work perfect

**Comment by PabloRNC** [comment]
Awesome.
